### ISSUE TITLE
建议修改BlogController.java文件的逻辑错误

### ISSUE THREAD

**Issue by 0x522** [blindpirate/xiedaimala-springboot#8]
`private Blog fromParam(Map<String, String> params, User user) {
        Blog blog = new Blog();
        String title = params.get("title");
        String content = params.get("content");
        String description = params.get("description");

        AssertUtils.assertTrue(StringUtils.isNotBlank(title) && title.length() < 100, "title is invalid!");
        AssertUtils.assertTrue(StringUtils.isNotBlank(content) && content.length() < 10000, "content is invalid");

        if (StringUtils.isBlank(description)) {
            description = content.substring(0, Math.min(content.length(), 10)) + "...";
        }

        blog.setTitle(title);
        blog.setContent(content);
        blog.setDescription(description);
        blog.setUser(user);
        return blog;
    }`
`AssertUtils.assertTrue(StringUtils.isNotBlank(title) && title.length() < 100, "title is valid!");
 AssertUtils.assertTrue(StringUtils.isNotBlank(content) && content.length() < 10000, "content is valid");`
根据逻辑 title不为空且长度不小于100是有效值，content同理。

**Comment by blindpirate** [comment]
你误解了第二个字符串参数的意思，它并不是要解释第一个参数，而是“当条件无法满足时抛出的错误信息”，即，当内容无效时，抛出错误信息为"title is invalid!"的异常信息。

**Comment by 0x522** [comment]
> 你误解了第二个字符串参数的意思，它并不是要解释第一个参数，而是“当条件无法满足时抛出的错误信息”，即，当内容无效时，抛出错误信息为"title is invalid!"的异常信息。

刚看懂，谢谢提醒！
